name: 'Main'
on:
  - workflow_dispatch
  - push

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: lorenzolewis/github-script-test/.github/actions/create-or-update-branch@main
