name: 'Main'
on:
  - workflow_dispatch
  - push

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: lorenzolewis/github-script-test/create-or-update-branch@main
        with:
          branch-name: 'i18n-preview'
      - uses: lorenzolewis/github-script-test/create-pull-request@main
        with:
          head: 'i18n-preview'
          base: main
